# Generated by Django 4.1.4 on 2022-12-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
