# Generated by Django 4.1.4 on 2022-12-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0002_annonce_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='supprimé',
            field=models.BooleanField(default=False),
        ),
    ]
