# Generated by Django 4.1.4 on 2023-01-02 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0003_annonce_supprimé'),
    ]

    operations = [
        migrations.CreateModel(
            name='scrupted_annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50)),
                ('nature', models.CharField(max_length=50)),
                ('annctype', models.CharField(max_length=50)),
                ('prix', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='annonce',
            name='img',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
    ]
