# Generated by Django 4.1.4 on 2023-01-02 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0003_annonce_supprimé'),
    ]

    operations = [
        migrations.CreateModel(
            name='bien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wilaya', models.CharField(max_length=100)),
                ('commune', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=35)),
                ('description', models.TextField(max_length=200, null=True)),
                ('localisation', models.CharField(max_length=60)),
                ('prix', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('google_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('sim1', models.CharField(max_length=10)),
                ('sim2', models.CharField(max_length=10)),
                ('localisation', models.CharField(max_length=60)),
                ('username', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='annonce',
            name='description',
        ),
        migrations.RemoveField(
            model_name='annonce',
            name='img',
        ),
        migrations.RemoveField(
            model_name='annonce',
            name='localisation',
        ),
        migrations.RemoveField(
            model_name='annonce',
            name='prix',
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField()),
                ('id_expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='annonces.utilisateur')),
                ('id_receveur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='annonces.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='ImagesUtilisateurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='images/default.png', upload_to='images_users/')),
                ('id_utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annonces.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='ImagesAnnonces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='images/default.png', upload_to='images/')),
                ('id_annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annonces.annonce')),
            ],
        ),
        migrations.AddField(
            model_name='annonce',
            name='id_annonceur',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='annonces.utilisateur'),
        ),
        migrations.AddField(
            model_name='annonce',
            name='lebien',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='annonces.bien'),
        ),
    ]
