# Generated by Django 4.1.4 on 2023-02-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0004_bien_utilisateur_remove_annonce_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='google_id',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='email',
            field=models.CharField(default='test.com', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='id',
            field=models.BigAutoField(auto_created=True, default=100, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagesannonces',
            name='img',
            field=models.ImageField(default='images/default.png', upload_to='images_annonces/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='msg',
            field=models.TextField(null=True),
        ),
    ]
