# Generated by Django 4.1.4 on 2023-01-05 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0005_rename_annctype_scrupted_annonce_adresse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrupted_annonce',
            name='surface',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='scrupted_annonce',
            name='adresse',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='scrupted_annonce',
            name='categorie',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='scrupted_annonce',
            name='localisation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='scrupted_annonce',
            name='prix',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
