# Generated by Django 4.1.4 on 2023-01-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0006_scrupted_annonce_surface_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrupted_annonce',
            name='img',
            field=models.ImageField(default='images/default.png', null=True, upload_to='images/'),
        ),
    ]
